import DOMAIN_CATEGORIES from "../../../enums/DomainCategoryEnums";
import {
  IMPORTANCE_OPTS,
  JOURNAL_FORMAT,
  JOURNAL_STATUS_OPTS,
  OPEN_ACCESS_OPTS,
} from "../../../enums/JournalEnums";
import { EntityNames } from "../../../services/entities";

export const JOURNAL_CONFIG = [
  { title: "Journal ID", key: "id", dataIndex: "id" },
  { title: "Journal Title", key: "title", dataIndex: "title" },
  { title: "Short Title", key: "short_title", dataIndex: "short_title" },
  { title: "Acronym", key: "acronym", dataIndex: "acronym" },
  {
    title: "Journal Status",
    key: "journal_status",
    dataIndex: "journal_status",
    type: "dropdown",
    options: JOURNAL_STATUS_OPTS,
  },
  { title: "Journal Owner", key: "journal_owner", dataIndex: "journal_owner" },
  {
    title: "Journal Type",
    key: "journal_article_info.submission.domain_value",
    dataIndex: "journal_article_info.submission.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.SUBMISSION,
  },
  {
    title: "Publication Mode",
    key: "journal_issue_info.pub_mode",
    dataIndex: "journal_issue_info.pub_mode.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.PUB_MODE,
  },
  {
    title: "Journal Importance",
    key: "importance",
    dataIndex: "importance",
    type: "dropdown",
    options: IMPORTANCE_OPTS,
  },
  { title: "Journal Email", key: "email", dataIndex: "email" },
  { title: "Journal Signature", key: "signature", dataIndex: "signature" },
  {
    title: "Journal Language",
    key: "lang_id",
    children: [
      {
        title: "Language",
        key: "lang_name",
        dataIndex: "lang_id.lang_name",
        type: "dropdown",
        entity: EntityNames.LANGUAGE,
      },
    ],
  },
  {
    title: "House Style",
    key: "house_style_id",
    children: [
      {
        title: "House Style",
        key: "house_style_name",
        dataIndex: "house_style_id.house_style_name",
        type: "dropdown",
        entity: EntityNames.HOUSE_STYLE,
      },
    ],
  },
  { title: "Journal CODEN", key: "coden", dataIndex: "coden" },
  {
    title: "Journal Format",
    key: "journal_format",
    dataIndex: "journal_format",
    type: "dropdown",
    options: JOURNAL_FORMAT,
  },
  {
    title: "Partner",
    key: "partner_id",
    children: [
      {
        title: "Partner",
        key: "partner_name",
        dataIndex: "partner_id.partner_name",
        type: "dropdown",
        entity: EntityNames.PARTNER,
      },
      {
        title: "Partner Contact",
        key: "partner_contact_id",
        dataIndex: "partner_contact_id.id",
        type: "dropdown",
        entity: EntityNames.USER,
        labelKey: "fname",
      },
    ],
  },
  {
    title: "Supplier",
    key: "supplier_id",
    children: [
      {
        title: "Supplier",
        key: "cvs_name",
        dataIndex: "supplier_id.cvs_name",
        type: "dropdown",
        entity: EntityNames.CVSDetails,
      },
      {
        title: "Supplier Contact",
        key: "supplier_contact_id",
        dataIndex: "supplier_contact_id.id",
        type: "dropdown",
        entity: EntityNames.USER,
        labelKey: "fname",
      },
    ],
  },
  {
    title: "Workflow",
    key: "journal_workflows",
    children: [
      {
        title: "Article Workflow",
        key: "journal_workflows.article",
        dataIndex: "journal_workflows.article.id",
        type: "dropdown",
        entity: EntityNames.JOURNAL_WORKFLOW,
        labelKey: "workflow_alias",
      },
      {
        title: "Issue Workflow",
        key: "journal_workflows.issue",
        dataIndex: "journal_workflows.issue.id",
        type: "dropdown",
        entity: EntityNames.JOURNAL_WORKFLOW,
        labelKey: "workflow_alias",
      },
    ],
  },
  {
    title: "Journal Online Code",
    key: "online_code",
    dataIndex: "online_code",
  },
  { title: "Online ISSN", key: "online_issn", dataIndex: "online_issn" },
  { title: "Print ISSN", key: "print_issn", dataIndex: "print_issn" },
  { title: "Primary ISSN", key: "primary_issn", dataIndex: "primary_issn" },
  {
    title: "OA Status/Open Access Type",
    key: "journal_article_info.oa_type",
    dataIndex: "journal_article_info.oa_type",
    type: "dropdown",
    options: OPEN_ACCESS_OPTS,
  },
  {
    title: "Free Access Type",
    key: "journal_article_info.fa_type",
    dataIndex: "journal_article_info.fa_type.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.FA_TYPE,
  },
  {
    title: "Free Access Start Date",
    key: "journal_article_info.fa_start",
    dataIndex: "journal_article_info.fa_start.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.FA_START_DATE,
  },
  {
    title: "Free Access End Date",
    key: "journal_article_info.fa_end",
    dataIndex: "journal_article_info.fa_end.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.FA_END_DATE,
  },
  {
    title: "Production Mode",
    key: "prod_mode.domain_value",
    dataIndex: "prod_mode.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.PROD_MODE,
  },
  {
    title: "Trim Size",
    key: "journal_article_info.trim_size.domain_value",
    dataIndex: "journal_article_info.trim_size.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.TRIM_SIZE,
  },
  {
    title: "Article Categories",
    key: "journal_article_info.journal_article_type.article_type_id.article_category_id.id",
    dataIndex:
      "journal_article_info.journal_article_type.article_type_id.article_category_id.id",
    type: "dropdown",
    entity: EntityNames.ARTICLE_CATEGORY,
    labelKey: "category_name",
  },
  {
    title: "Created On",
    key: "created_on",
    dataIndex: "created_on",
    type: "dateTime",
  },
  {
    title: "Modified On",
    key: "updated_on",
    dataIndex: "updated_on",
    type: "dateTime",
  },
  {
    title: "Created By",
    key: "created_by",
    dataIndex: "created_by.id",
    type: "dropdown",
    entity: EntityNames.USER,
    labelKey: "fname",
  },
  {
    title: "Modified By",
    key: "updated_by",
    dataIndex: "updated_by.id",
    type: "dropdown",
    entity: EntityNames.USER,
    labelKey: "fname",
  },
];

export const JOURNAL_METADATA_FIELDS = [
  {
    title: "Status",
    key: "journal_status",
    dataIndex: "journal_status",
    type: "dropdown",
    options: JOURNAL_STATUS_OPTS,
  },
  {
    title: "Journal Type",
    key: "journal_article_info.submission.domain_value",
    dataIndex: "journal_article_info.submission.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.SUBMISSION,
  },
  {
    title: "Journal Code",
    key: "acronym",
    dataIndex: "acronym",
    type: "dropdown",
    entity: EntityNames.JOURNAL,
  },
  { title: "Journal Title", key: "title", dataIndex: "title" },
  { title: "Journal Subtitle", key: "short_title", dataIndex: "short_title" },
  { title: "Online ISSN", key: "online_issn", dataIndex: "online_issn" },
  { title: "Print ISSN", key: "print_issn", dataIndex: "print_issn" },
  {
    title: "Publisher",
    key: "partner_name",
    dataIndex: "partner_id.partner_name",
    type: "dropdown",
    entity: EntityNames.PARTNER,
  },
  { title: "Owner", key: "journal_owner", dataIndex: "journal_owner" },
  {
    title: "Publication Mode",
    key: "journal_issue_info.pub_mode",
    dataIndex: "journal_issue_info.pub_mode.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.PUB_MODE,
  },
  {
    title: "OA Status/Open Access Type",
    key: "journal_article_info.oa_type",
    dataIndex: "journal_article_info.oa_type",
    type: "dropdown",
    options: OPEN_ACCESS_OPTS,
  },
  {
    title: "Free Access Type",
    key: "journal_article_info.fa_type",
    dataIndex: "journal_article_info.fa_type.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.FA_TYPE,
  },
  {
    title: "Free Access End Date",
    key: "journal_article_info.fa_end",
    dataIndex: "journal_article_info.fa_end.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.FA_END_DATE,
  },
  {
    title: "Journal Online Code",
    key: "online_code",
    dataIndex: "online_code",
  },
  {
    title: "Production Mode",
    key: "prod_mode.domain_value",
    dataIndex: "prod_mode.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.PROD_MODE,
  },
  {
    title: "Issue Workflow",
    key: "journal_workflows.issue",
    dataIndex: "journal_workflows.issue.id",
    type: "dropdown",
    entity: EntityNames.JOURNAL_WORKFLOW,
    labelKey: "workflow_alias",
  },
  {
    title: "Article Workflow",
    key: "journal_workflows.article",
    dataIndex: "journal_workflows.article.id",
    type: "dropdown",
    entity: EntityNames.JOURNAL_WORKFLOW,
    labelKey: "workflow_alias",
  },
  {
    title: "Trim Size",
    key: "journal_article_info.trim_size.domain_value",
    dataIndex: "journal_article_info.trim_size.domain_value",
    type: "dropdown",
    entity: EntityNames.DOMAIN,
    labelKey: "domain_value",
    domainCategory: DOMAIN_CATEGORIES.TRIM_SIZE,
  },
  {
    title: "Article Categories",
    key: "journal_article_info.journal_article_type.article_type_id.article_category_id.id",
    dataIndex:
      "journal_article_info.journal_article_type.article_type_id.article_category_id.id",
    type: "dropdown",
    entity: EntityNames.ARTICLE_CATEGORY,
    labelKey: "category_name",
  },
  {
    title: "Company (Conversion Vendor)",
    key: "cvs_name",
    dataIndex: "supplier_id.cvs_name",
    type: "dropdown",
    entity: EntityNames.CVSDetails,
  },
  {
    title: "Supplier Contact",
    key: "supplier_contact_id",
    dataIndex: "supplier_contact_id.id",
    type: "dropdown",
    entity: EntityNames.USER,
    labelKey: "fname",
  },
];
